print("hello ruban")
text = ("Hello Ruban, welcome to Python programming")
print(text)
print(text[0])
print(text[-1])
print(text[0:6])
print(text[-1:-12:-1])
print(f'Reverse tuple:{text[::-1]}')
print(text[24:30])
strM = "Python beginner tutorial"
print(strM.upper())
print(strM.lower())
strM_capitalized = strM.capitalize()
print(strM_capitalized)
count_t = strM.count('t')
print(count_t)
new_str = strM.replace("Python", "Machine Learning")
print(new_str)
tuples=(10,20,30)
tuples1=(40,50,60)
print(tuples)
print(tuples1)
t_combine = tuples + tuples1
print(t_combine)
t_combine = (tuples + tuples1)*3
print(t_combine)
print(t_combine[2])
print(t_combine[0:3])
print(t_combine[:-4:-1])